### ISSUE TITLE
Adding a new task according to proposed Llama3

### ISSUE THREAD

**Issue by pavaris-pm** [PyThaiNLP/thaipromptnlp#1]
@wannaphong Big thanks to one of the very good repo of Thai prompting! 

I've seen that you added a prompt that was experimented with `llama3` in huggingface as stated. Anyway, do you have any other task preferred to add?

if you're not, i want to try it with knowledge graph extraction capabilities since it was interesting in other languages. if it bring a good or acceptable performance, i will make a PR to this repo. Do you agree with this?

**Comment by wannaphong** [comment]
Yes, you can. 👍

**Comment by pavaris-pm** [comment]
closing this since my knowledge graph extraction task for prompting with llama3 already, it works pretty cool! i will com back if i have any new ideas for sure krub 👍🏻
